# Generated by Django 2.2.5 on 2019-09-09 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=30)),
                ('class_coordinator_name', models.CharField(max_length=30)),
                ('strength', models.IntegerField()),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=30)),
                ('dept_HOD', models.CharField(max_length=30)),
                ('dept_strength', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parent_id', models.IntegerField(primary_key=True, serialize=False)),
                ('parent_name', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('contact_no', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=30)),
                ('semester', models.IntegerField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stud_pro.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Subject',
            fields=[
                ('sr_no', models.IntegerField(primary_key=True, serialize=False)),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stud_pro.Subject')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stud_pro.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('attendance', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stud_pro.Class')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stud_pro.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='Class_Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stud_pro.Class')),
                ('sr_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stud_pro.Teacher_Subject')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stud_pro.Department'),
        ),
        migrations.CreateModel(
            name='Attendance_Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stud_pro.Student')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stud_pro.Subject')),
            ],
        ),
    ]
