# Generated by Django 2.2.5 on 2019-09-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_pro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
