# Generated by Django 2.2.1 on 2019-09-11 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stud_pro', '0003_auto_20190911_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_marks',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_pro.Student'),
        ),
        migrations.AlterField(
            model_name='attendance_marks',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_pro.Subject'),
        ),
        migrations.AlterField(
            model_name='class',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_pro.Department'),
        ),
        migrations.AlterField(
            model_name='class_teacher',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_pro.Class'),
        ),
        migrations.AlterField(
            model_name='class_teacher',
            name='sr_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_pro.Teacher_Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_pro.Department'),
        ),
        migrations.AlterField(
            model_name='teacher_subject',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_pro.Subject'),
        ),
        migrations.AlterField(
            model_name='teacher_subject',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_pro.Teacher'),
        ),
    ]
