# Generated by Django 2.2.5 on 2019-09-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_pro', '0004_auto_20190911_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_subject',
            name='sr_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
