# Generated by Django 2.2.1 on 2019-09-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_pro', '0005_auto_20190912_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contact_no',
            field=models.CharField(default='-', max_length=15),
        ),
        migrations.AlterField(
            model_name='parent',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parent',
            name='contact_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
