# Generated by Django 2.2.1 on 2019-09-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_pro', '0006_auto_20190912_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='occupation',
            field=models.CharField(max_length=80),
        ),
    ]
