# Generated by Django 2.2.1 on 2019-09-12 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stud_pro', '0007_auto_20190912_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stud_pro.Class'),
        ),
    ]
