# Generated by Django 2.2.5 on 2019-09-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_pro', '0005_auto_20190915_0310'),
        ('stud_pro', '0008_auto_20190912_2054'),
    ]

    operations = [
    ]
